// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.forms */
export type FormsId = number & { __brand: 'public.forms' };

/** Represents the table public.forms */
export default interface Forms {
  id: FormsId;

  title: string;

  description: string | null;

  is_public: boolean | null;

  is_published: boolean | null;

  is_accepting_responses: boolean | null;

  require_login: boolean | null;

  allow_multiple_responses: boolean | null;

  show_progress_bar: boolean | null;

  theme_color: string | null;

  background_color: string | null;

  header_image_url: string | null;

  confirmation_message: string | null;

  redirect_url: string | null;

  email_notifications: boolean | null;

  elements: unknown | null;

  total_responses: number | null;

  view_count: number | null;

  created_at: Date | null;

  updated_at: Date | null;

  published_at: Date | null;

  expires_at: Date | null;

  user_id: string | null;
}

/** Represents the initializer for the table public.forms */
export interface FormsInitializer {
  /** Default value: nextval('forms_id_seq'::regclass) */
  id?: FormsId;

  title: string;

  description?: string | null;

  /** Default value: false */
  is_public?: boolean | null;

  /** Default value: false */
  is_published?: boolean | null;

  /** Default value: true */
  is_accepting_responses?: boolean | null;

  /** Default value: false */
  require_login?: boolean | null;

  /** Default value: true */
  allow_multiple_responses?: boolean | null;

  /** Default value: false */
  show_progress_bar?: boolean | null;

  /** Default value: '#1a73e8'::character varying */
  theme_color?: string | null;

  /** Default value: '#ffffff'::character varying */
  background_color?: string | null;

  header_image_url?: string | null;

  /** Default value: 'Your response has been recorded.'::text */
  confirmation_message?: string | null;

  redirect_url?: string | null;

  /** Default value: false */
  email_notifications?: boolean | null;

  /** Default value: '[]'::jsonb */
  elements?: unknown | null;

  /** Default value: 0 */
  total_responses?: number | null;

  /** Default value: 0 */
  view_count?: number | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;

  published_at?: Date | null;

  expires_at?: Date | null;

  user_id?: string | null;
}

/** Represents the mutator for the table public.forms */
export interface FormsMutator {
  id?: FormsId;

  title?: string;

  description?: string | null;

  is_public?: boolean | null;

  is_published?: boolean | null;

  is_accepting_responses?: boolean | null;

  require_login?: boolean | null;

  allow_multiple_responses?: boolean | null;

  show_progress_bar?: boolean | null;

  theme_color?: string | null;

  background_color?: string | null;

  header_image_url?: string | null;

  confirmation_message?: string | null;

  redirect_url?: string | null;

  email_notifications?: boolean | null;

  elements?: unknown | null;

  total_responses?: number | null;

  view_count?: number | null;

  created_at?: Date | null;

  updated_at?: Date | null;

  published_at?: Date | null;

  expires_at?: Date | null;

  user_id?: string | null;
}
