// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FormsId } from './Forms';

/** Identifier type for public.responses */
export type ResponsesId = number & { __brand: 'public.responses' };

/** Represents the table public.responses */
export default interface Responses {
  id: ResponsesId;

  form_id: FormsId | null;

  respondent_email: string | null;

  respondent_name: string | null;

  response_data: unknown | null;

  ip_address: string | null;

  user_agent: string | null;

  completion_time_seconds: number | null;

  created_at: Date | null;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.responses */
export interface ResponsesInitializer {
  /** Default value: nextval('responses_id_seq'::regclass) */
  id?: ResponsesId;

  form_id?: FormsId | null;

  respondent_email?: string | null;

  respondent_name?: string | null;

  /** Default value: '{}'::jsonb */
  response_data?: unknown | null;

  ip_address?: string | null;

  user_agent?: string | null;

  completion_time_seconds?: number | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;
}

/** Represents the mutator for the table public.responses */
export interface ResponsesMutator {
  id?: ResponsesId;

  form_id?: FormsId | null;

  respondent_email?: string | null;

  respondent_name?: string | null;

  response_data?: unknown | null;

  ip_address?: string | null;

  user_agent?: string | null;

  completion_time_seconds?: number | null;

  created_at?: Date | null;

  updated_at?: Date | null;
}
