// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.users */
export type UsersId = number & { __brand: 'public.users' };

/** Represents the table public.users */
export default interface Users {
  id: UsersId;

  clerk_user_id: string;

  email_addresses: unknown | null;

  phone_numbers: unknown | null;

  first_name: string | null;

  last_name: string | null;

  username: string | null;

  profile_image_url: string | null;

  image_url: string | null;

  has_image: boolean | null;

  banned: boolean | null;

  locked: boolean | null;

  email_verification_attempts: number | null;

  phone_verification_attempts: number | null;

  external_accounts: unknown | null;

  external_id: string | null;

  email_verified: boolean | null;

  phone_verified: boolean | null;

  two_factor_enabled: boolean | null;

  created_at_clerk: Date | null;

  updated_at_clerk: Date | null;

  last_sign_in_at: Date | null;

  last_active_at: Date | null;

  private_metadata: unknown | null;

  public_metadata: unknown | null;

  unsafe_metadata: unknown | null;

  gender: string | null;

  birthday: Date | null;

  web3_wallets: unknown | null;

  saml_accounts: unknown | null;

  created_at: Date | null;

  updated_at: Date | null;

  is_active: boolean | null;

  webhook_received_at: Date | null;

  webhook_event_type: string | null;

  raw_webhook_data: unknown | null;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  /** Default value: nextval('users_id_seq'::regclass) */
  id?: UsersId;

  clerk_user_id: string;

  email_addresses?: unknown | null;

  phone_numbers?: unknown | null;

  first_name?: string | null;

  last_name?: string | null;

  username?: string | null;

  profile_image_url?: string | null;

  image_url?: string | null;

  /** Default value: false */
  has_image?: boolean | null;

  /** Default value: false */
  banned?: boolean | null;

  /** Default value: false */
  locked?: boolean | null;

  /** Default value: 0 */
  email_verification_attempts?: number | null;

  /** Default value: 0 */
  phone_verification_attempts?: number | null;

  /** Default value: '[]'::jsonb */
  external_accounts?: unknown | null;

  external_id?: string | null;

  /** Default value: false */
  email_verified?: boolean | null;

  /** Default value: false */
  phone_verified?: boolean | null;

  /** Default value: false */
  two_factor_enabled?: boolean | null;

  created_at_clerk?: Date | null;

  updated_at_clerk?: Date | null;

  last_sign_in_at?: Date | null;

  last_active_at?: Date | null;

  /** Default value: '{}'::jsonb */
  private_metadata?: unknown | null;

  /** Default value: '{}'::jsonb */
  public_metadata?: unknown | null;

  /** Default value: '{}'::jsonb */
  unsafe_metadata?: unknown | null;

  gender?: string | null;

  birthday?: Date | null;

  /** Default value: '[]'::jsonb */
  web3_wallets?: unknown | null;

  /** Default value: '[]'::jsonb */
  saml_accounts?: unknown | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;

  /** Default value: true */
  is_active?: boolean | null;

  /** Default value: CURRENT_TIMESTAMP */
  webhook_received_at?: Date | null;

  webhook_event_type?: string | null;

  raw_webhook_data?: unknown | null;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId;

  clerk_user_id?: string;

  email_addresses?: unknown | null;

  phone_numbers?: unknown | null;

  first_name?: string | null;

  last_name?: string | null;

  username?: string | null;

  profile_image_url?: string | null;

  image_url?: string | null;

  has_image?: boolean | null;

  banned?: boolean | null;

  locked?: boolean | null;

  email_verification_attempts?: number | null;

  phone_verification_attempts?: number | null;

  external_accounts?: unknown | null;

  external_id?: string | null;

  email_verified?: boolean | null;

  phone_verified?: boolean | null;

  two_factor_enabled?: boolean | null;

  created_at_clerk?: Date | null;

  updated_at_clerk?: Date | null;

  last_sign_in_at?: Date | null;

  last_active_at?: Date | null;

  private_metadata?: unknown | null;

  public_metadata?: unknown | null;

  unsafe_metadata?: unknown | null;

  gender?: string | null;

  birthday?: Date | null;

  web3_wallets?: unknown | null;

  saml_accounts?: unknown | null;

  created_at?: Date | null;

  updated_at?: Date | null;

  is_active?: boolean | null;

  webhook_received_at?: Date | null;

  webhook_event_type?: string | null;

  raw_webhook_data?: unknown | null;
}
